### ISSUE TITLE
%files section with unneeded entries

### ISSUE THREAD

**Issue by dlage** [silug/cpanspec#8]
Some modules don't have any /bin/ or /man3/ entries. The previous release didn't cause any troubles but the latest (taken from master branch) causes the spec file to include too many entries in the `%files` section, which causes `rpmbuild` to error out:

```
RPM build errors:
    File not found by glob: /home/rpmbuild/rpmbuild/BUILDROOT/perl-Mojolicious-Plugin-TtRenderer-1.56-1.el7.centos.x86_64/usr/bin/*
    File not found by glob: /home/rpmbuild/rpmbuild/BUILDROOT/perl-Mojolicious-Plugin-TtRenderer-1.56-1.el7.centos.x86_64/usr/share/man/man1/*
```

With latest version:

```
%files
%defattr(-,root,root,-)
%doc Changes cpanfile example LICENSE README
%{_bindir}/*
%{_mandir}/man1/*
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
- Specfile autogenerated by cpanspec 1.79.
```

And with the previous:

```
%files
%defattr(-,root,root,-)
%doc Changes cpanfile dist.ini example LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
- Specfile autogenerated by cpanspec 1.78.
```

I didn't have time to investigate the issue further but will try to make a PR later this week if no fix is made meanwhile.

**Comment by dlage** [comment]
Related PR https://github.com/silug/cpanspec/pull/9

**Comment by silug** [comment]
Merged pull request.
